export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const RECEIVED_PRODUCTS = 'RECEIVED_PRODUCTS';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const SHOW_PRODUCT_DETAIL = 'SHOW_PRODUCT_DETAIL';
export const REQUEST_SEARCH_PRODUCTS = 'REQUEST_SEARCH_PRODUCTS';
